FROM quay.io/keycloak/keycloak:25.0

# Copy realm configuration for importing on startup
COPY ./docker/keycloak/realm-iitd.json /opt/keycloak/data/import/realm-iitd.json

# Copy custom login themes
COPY ./keycloak/themes/iitd /opt/keycloak/themes/iitd

# Configure Keycloak HTTP port to match Hugging Face standard
EXPOSE 7860

# Run Keycloak start-dev command
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-port=7860", "--import-realm"]
